import { createFileRoute } from "@tanstack/react-router";
import LegalPage from "@/components/LegalPage";

const title = "Politique de confidentialité | TRADEMARK";
const description = "Politique de confidentialité de TRADEMARK : données recueillies, usages, conservation, cookies et droits des personnes.";

export const Route = createFileRoute("/confidentialite")({
  head: () => ({
    meta: [
      { title }, { name: "description", content: description },
      { property: "og:type", content: "website" }, { property: "og:title", content: title },
      { property: "og:description", content: description }, { name: "twitter:card", content: "summary" },
      { name: "twitter:title", content: title }, { name: "twitter:description", content: description },
    ],
    links: [
      { rel: "canonical", href: "https://www.tmrk.fr/confidentialite/" },
      { rel: "alternate", hrefLang: "fr", href: "https://www.tmrk.fr/confidentialite/" },
      { rel: "alternate", hrefLang: "en", href: "https://www.tmrk.fr/en/privacy/" },
    ],
  }),
  component: PrivacyPolicy,
});

function PrivacyPolicy() {
  return (
    <LegalPage language="fr" eyebrow="Données personnelles" title="Politique de confidentialité" updated="Dernière mise à jour : 24 septembre 2026" alternatePath="/en/privacy">
      <div className="legal-intro"><p>Cette page explique quelles informations personnelles nous recueillons quand vous utilisez le site www.tmrk.fr, ce que nous en faisons, combien de temps nous les gardons et quels sont vos droits.</p><p>Nous appliquons le Règlement général sur la protection des données (RGPD), le texte européen qui encadre l’usage des données personnelles, ainsi que la loi française « Informatique et Libertés ».</p></div>
      <section><h2>1. Qui est responsable de vos données ?</h2><p><strong>TRADEMARK</strong>, SASU au capital de 1 000 euros, 134-136 boulevard Brune, 75014 Paris, France.</p><p>C’est TRADEMARK qui décide pourquoi et comment vos données sont utilisées. Pour toute question : <strong><a href="mailto:contact@tmrk.fr">contact@tmrk.fr</a></strong>.</p></section>
      <section><h2>2. Quelles données recueillons-nous ?</h2><p><strong>Quand vous remplissez le formulaire de contact :</strong> votre prénom, votre nom, le nom de votre entreprise, votre adresse e-mail et l’objet de votre demande, ainsi que tout ce que vous choisissez de nous écrire.</p><p><strong>Quand vous nous écrivez directement</strong> à contact@tmrk.fr : votre adresse e-mail et le contenu de votre message.</p><p><strong>Quand vous visitez le site :</strong> notre hébergeur enregistre automatiquement quelques informations techniques, comme votre adresse IP (le numéro qui identifie votre connexion à internet), la date et l’heure de votre visite, les pages consultées et le type de navigateur utilisé. Ces « journaux de connexion » servent à faire fonctionner le site et à le protéger.</p><p>Nous ne vous demandons aucune donnée sensible (santé, opinions politiques ou religieuses, etc.). Merci de ne pas en indiquer dans vos messages.</p></section>
      <section><h2>3. Pourquoi les utilisons-nous ?</h2><p>La loi nous oblige à indiquer, pour chaque usage, la raison qui nous autorise à traiter vos données (on parle de « base légale »).</p><div className="legal-table-wrap"><table><thead><tr><th>Ce que nous faisons</th><th>Ce qui nous y autorise</th></tr></thead><tbody><tr><td>Répondre à votre demande et échanger avec vous</td><td>Notre intérêt légitime à répondre aux personnes qui nous contactent ou, si vous envisagez de travailler avec nous, les échanges préalables à un contrat que vous avez sollicités</td></tr><tr><td>Suivre la relation avec les entreprises qui travaillent avec nous</td><td>Le contrat qui nous lie</td></tr><tr><td>Assurer la sécurité et le bon fonctionnement du site</td><td>Notre intérêt légitime à protéger le site</td></tr><tr><td>Mesurer la fréquentation du site <strong>[À SUPPRIMER si le site n’utilise pas d’outil de mesure]</strong></td><td>Votre accord, que vous pouvez retirer à tout moment</td></tr></tbody></table></div><p>Nous n’utilisons vos coordonnées que pour échanger avec vous. Nous ne vous inscrivons à aucune lettre d’information sans votre accord.</p></section>
      <section><h2>4. Qui peut voir vos données ?</h2><ul><li><strong>Les membres de l’équipe TRADEMARK</strong> chargés de votre demande, y compris, lorsque votre demande concerne leur marché, nos équipes de Casablanca (Maroc) et d’Abidjan (Côte d’Ivoire).</li><li><strong>Nos prestataires techniques</strong>, uniquement pour nous rendre service : OVH, qui héberge le site et nous transmet par e-mail les messages envoyés par le formulaire, et notre fournisseur de messagerie électronique. Ils ont interdiction d’utiliser vos données pour leur propre compte.</li></ul><p>Nous ne vendons, ne louons et n’échangeons jamais vos données.</p></section>
      <section><h2>5. Vos données quittent-elles l’Europe ?</h2><p>Le site est hébergé en Europe par OVH. Vos données peuvent toutefois être transmises hors de l’Union européenne dans deux cas :</p><ul><li>lorsque votre demande est suivie par nos équipes de Casablanca ou d’Abidjan ;</li><li>lorsqu’un de nos prestataires techniques traite des données hors d’Europe.</li></ul><p>Ces transferts sont alors protégés par l’une des garanties prévues par le RGPD : soit une décision de la Commission européenne reconnaissant que le pays de destination protège correctement les données, soit des « clauses contractuelles types », c’est-à-dire un contrat modèle, rédigé par la Commission européenne, qui oblige le destinataire à protéger vos données comme en Europe. Vous pouvez en demander une copie à contact@tmrk.fr.</p></section>
      <section><h2>6. Combien de temps les gardons-nous ?</h2><ul><li><strong>Demande de contact restée sans suite :</strong> 3 ans après notre dernier échange.</li><li><strong>Clients et partenaires :</strong> pendant toute la durée de notre collaboration, puis 5 ans (le délai pendant lequel une action en justice reste possible). Les pièces comptables sont conservées 10 ans, comme la loi l’exige.</li><li><strong>Journaux de connexion :</strong> 1 an au maximum.</li><li><strong>Votre choix concernant les cookies :</strong> 6 mois.</li></ul><p>À la fin de ces délais, vos données sont supprimées ou rendues anonymes.</p></section>
      <section><h2>7. Vos droits</h2><p>Vous pouvez à tout moment :</p><ul><li><strong>savoir</strong> quelles données nous avons sur vous et en obtenir une copie ;</li><li>les faire <strong>corriger</strong> si elles sont fausses ou incomplètes ;</li><li>les faire <strong>effacer</strong> ;</li><li>vous <strong>opposer</strong> à leur utilisation, ou demander qu’elle soit <strong>limitée</strong> ;</li><li>les <strong>récupérer</strong> dans un format courant pour les transmettre à quelqu’un d’autre ;</li><li><strong>retirer votre accord</strong> lorsque nous vous l’avons demandé (pour les cookies, par exemple) ;</li><li>nous indiquer ce que vous souhaitez qu’il advienne de vos données <strong>après votre décès</strong>.</li></ul><p><strong>Pour exercer ces droits</strong>, écrivez-nous à contact@tmrk.fr ou par courrier à TRADEMARK, 134-136 boulevard Brune, 75014 Paris. Nous vous répondrons dans un délai d’un mois. En cas de doute sur votre identité, nous pourrons vous demander un justificatif.</p><p>Si vous estimez que vos droits ne sont pas respectés, vous pouvez vous adresser à la CNIL (Commission nationale de l’informatique et des libertés), l’autorité française chargée de la protection des données : <a href="https://www.cnil.fr" rel="noreferrer">www.cnil.fr</a>, ou 3 place de Fontenoy, TSA 80715, 75334 Paris Cedex 07.</p></section>
      <section><h2>8. Cookies</h2><p>Un cookie est un petit fichier déposé sur votre ordinateur ou votre téléphone quand vous visitez un site. Il permet au site de se souvenir de certaines informations d’une visite à l’autre.</p><div className="legal-table-wrap"><table><thead><tr><th>Cookie</th><th>À quoi il sert</th><th>Durée</th><th>Votre accord est-il demandé ?</th></tr></thead><tbody><tr><td>Mémorisation de votre choix</td><td>Retenir si vous avez accepté ou refusé les cookies, pour ne pas vous reposer la question à chaque visite</td><td>6 mois</td><td>Non, il est indispensable</td></tr><tr><td><strong>[À COMPLÉTER : nom de l’outil de mesure de fréquentation — ou supprimer cette ligne si le site n’en utilise pas]</strong></td><td>Compter les visites et savoir quelles pages sont les plus lues, pour améliorer le site</td><td>13 mois au maximum</td><td>Oui</td></tr></tbody></table></div><p>Le site n’utilise ni cookies publicitaires, ni cookies de réseaux sociaux.</p><p>Vous pouvez changer d’avis à tout moment grâce au lien <strong>« Gestion des cookies »</strong>, en bas de chaque page. Vous pouvez aussi bloquer ou supprimer les cookies dans les réglages de votre navigateur.</p></section>
      <section><h2>9. Sécurité</h2><p>Le site utilise une connexion sécurisée (HTTPS, signalée par un cadenas dans la barre d’adresse de votre navigateur) : les informations que vous envoyez par le formulaire sont chiffrées pendant leur transmission. L’accès aux messages reçus est réservé aux personnes qui en ont besoin pour vous répondre.</p></section>
      <section><h2>10. Modifications de cette page</h2><p>Nous pouvons mettre à jour cette politique, par exemple si le site évolue. La date de la dernière mise à jour figure en haut de la page.</p></section>
    </LegalPage>
  );
}