import { createFileRoute } from "@tanstack/react-router";
import LegalPage from "@/components/LegalPage";

const title = "Privacy Policy | TRADEMARK";
const description = "TRADEMARK privacy policy: data collected, purposes, retention periods, cookies and individual rights.";

export const Route = createFileRoute("/en/privacy")({
  head: () => ({
    meta: [
      { title }, { name: "description", content: description },
      { property: "og:type", content: "website" }, { property: "og:title", content: title },
      { property: "og:description", content: description }, { name: "twitter:card", content: "summary" },
      { name: "twitter:title", content: title }, { name: "twitter:description", content: description },
    ],
    links: [
      { rel: "canonical", href: "https://www.tmrk.fr/en/privacy/" },
      { rel: "alternate", hrefLang: "fr", href: "https://www.tmrk.fr/confidentialite/" },
      { rel: "alternate", hrefLang: "en", href: "https://www.tmrk.fr/en/privacy/" },
    ],
  }),
  component: PrivacyPolicy,
});

function PrivacyPolicy() {
  return (
    <LegalPage language="en" eyebrow="Personal data" title="Privacy policy" updated="Last updated: 24 September 2026" alternatePath="/confidentialite">
      <div className="legal-intro"><p>This page explains what personal information we collect when you use www.tmrk.fr, what we do with it, how long we keep it and what rights you have.</p><p>We comply with the General Data Protection Regulation (GDPR), the European legislation governing the use of personal data, and the French Data Protection Act (“Informatique et Libertés”).</p></div>
      <section><h2>1. Who is responsible for your data?</h2><p><strong>TRADEMARK</strong>, a French simplified single-shareholder company (SASU) with share capital of €1,000, 134-136 boulevard Brune, 75014 Paris, France.</p><p>TRADEMARK decides why and how your data is used. If you have any questions, please contact <strong><a href="mailto:contact@tmrk.fr">contact@tmrk.fr</a></strong>.</p></section>
      <section><h2>2. What data do we collect?</h2><p><strong>When you complete the contact form:</strong> your first name, last name, company name, email address and the subject of your request, together with anything else you choose to write to us.</p><p><strong>When you email us directly</strong> at contact@tmrk.fr: your email address and the content of your message.</p><p><strong>When you visit the website:</strong> our hosting provider automatically records certain technical information, such as your IP address (the number that identifies your internet connection), the date and time of your visit, the pages viewed and the type of browser used. These “connection logs” help operate and protect the website.</p><p>We do not ask you to provide sensitive data (health information, political or religious opinions, etc.). Please do not include any such information in your messages.</p></section>
      <section><h2>3. Why do we use your data?</h2><p>The law requires us to state, for each use, the reason that permits us to process your data (known as the “legal basis”).</p><div className="legal-table-wrap"><table><thead><tr><th>What we do</th><th>What permits us to do so</th></tr></thead><tbody><tr><td>Respond to your request and communicate with you</td><td>Our legitimate interest in responding to people who contact us or, if you are considering working with us, the steps you requested before entering into a contract</td></tr><tr><td>Manage relationships with the companies that work with us</td><td>The contract between us</td></tr><tr><td>Maintain the security and proper operation of the website</td><td>Our legitimate interest in protecting the website</td></tr><tr><td>Measure website traffic <strong>[DELETE if the website does not use an analytics tool]</strong></td><td>Your consent, which you may withdraw at any time</td></tr></tbody></table></div><p>We use your contact details only to communicate with you. We do not subscribe you to any newsletter without your consent.</p></section>
      <section><h2>4. Who can see your data?</h2><ul><li><strong>TRADEMARK team members</strong> handling your request, including our teams in Casablanca (Morocco) and Abidjan (Côte d’Ivoire) when your request relates to their market.</li><li><strong>Our technical service providers</strong>, solely to provide services to us: OVH, which hosts the website and emails us the messages sent through the form, and our email provider. They are prohibited from using your data for their own purposes.</li></ul><p>We never sell, rent or exchange your data.</p></section>
      <section><h2>5. Does your data leave Europe?</h2><p>The website is hosted in Europe by OVH. Your data may nevertheless be transferred outside the European Union in two circumstances:</p><ul><li>when your request is handled by our teams in Casablanca or Abidjan;</li><li>when one of our technical service providers processes data outside Europe.</li></ul><p>These transfers are protected by one of the safeguards provided for by the GDPR: either a European Commission decision recognising that the destination country provides adequate data protection, or “standard contractual clauses”, a model agreement drafted by the European Commission that requires the recipient to protect your data as it would be protected in Europe. You may request a copy at contact@tmrk.fr.</p></section>
      <section><h2>6. How long do we keep your data?</h2><ul><li><strong>Contact request that does not lead to further action:</strong> 3 years after our last communication.</li><li><strong>Clients and partners:</strong> throughout our working relationship, then for 5 years (the period during which legal proceedings may be brought). Accounting records are retained for 10 years, as required by law.</li><li><strong>Connection logs:</strong> no more than 1 year.</li><li><strong>Your cookie choices:</strong> 6 months.</li></ul><p>At the end of these periods, your data is deleted or anonymised.</p></section>
      <section><h2>7. Your rights</h2><p>You may at any time:</p><ul><li><strong>find out</strong> what data we hold about you and obtain a copy;</li><li>have it <strong>corrected</strong> if it is inaccurate or incomplete;</li><li>have it <strong>deleted</strong>;</li><li><strong>object</strong> to its use or ask for its use to be <strong>restricted</strong>;</li><li><strong>receive it</strong> in a commonly used format so that you can transfer it to someone else;</li><li><strong>withdraw your consent</strong> when we have requested it (for cookies, for example);</li><li>tell us what you would like to happen to your data <strong>after your death</strong>.</li></ul><p><strong>To exercise these rights</strong>, email us at contact@tmrk.fr or write to TRADEMARK, 134-136 boulevard Brune, 75014 Paris, France. We will respond within one month. If we have doubts about your identity, we may ask you to provide proof of identity.</p><p>If you believe your rights have not been respected, you may contact the CNIL (Commission Nationale de l’Informatique et des Libertés), the French data protection authority: <a href="https://www.cnil.fr" rel="noreferrer">www.cnil.fr</a>, or 3 place de Fontenoy, TSA 80715, 75334 Paris Cedex 07, France.</p></section>
      <section><h2>8. Cookies</h2><p>A cookie is a small file placed on your computer or phone when you visit a website. It enables the website to remember certain information from one visit to the next.</p><div className="legal-table-wrap"><table><thead><tr><th>Cookie</th><th>Purpose</th><th>Duration</th><th>Is your consent required?</th></tr></thead><tbody><tr><td>Remembering your choice</td><td>Records whether you accepted or rejected cookies so that you are not asked again on every visit</td><td>6 months</td><td>No, it is essential</td></tr><tr><td><strong>[TO BE COMPLETED: name of the audience measurement tool — or delete this row if the website does not use one]</strong></td><td>Counts visits and identifies the most viewed pages in order to improve the website</td><td>No more than 13 months</td><td>Yes</td></tr></tbody></table></div><p>The website does not use advertising or social media cookies.</p><p>You can change your mind at any time using the <strong>“Cookie settings”</strong> link at the bottom of each page. You can also block or delete cookies in your browser settings.</p></section>
      <section><h2>9. Security</h2><p>The website uses a secure connection (HTTPS, shown by a padlock in your browser’s address bar): the information you submit through the form is encrypted during transmission. Access to received messages is restricted to those who need it in order to respond to you.</p></section>
      <section><h2>10. Changes to this policy</h2><p>We may update this policy, for example if the website changes. The date of the latest update appears at the top of the page.</p></section>
    </LegalPage>
  );
}